/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'selector',
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        surface: {
          DEFAULT: 'var(--surface)',
          raised: 'var(--surface-raised)',
          sunken: 'var(--surface-sunken)',
          overlay: 'var(--surface-overlay)',
        },
        border: {
          DEFAULT: 'var(--border)',
          strong: 'var(--border-strong)',
        },
        text: {
          DEFAULT: 'var(--text)',
          muted: 'var(--text-muted)',
          faint: 'var(--text-faint)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          strong: 'var(--accent-strong)',
          contrast: 'var(--accent-contrast)',
          wash: 'var(--accent-wash)',
        },
        status: {
          success: 'var(--status-success)',
          'success-wash': 'var(--status-success-wash)',
          failure: 'var(--status-failure)',
          'failure-wash': 'var(--status-failure-wash)',
          running: 'var(--status-running)',
          'running-wash': 'var(--status-running-wash)',
          pending: 'var(--status-pending)',
          'pending-wash': 'var(--status-pending-wash)',
          unknown: 'var(--status-unknown)',
          'unknown-wash': 'var(--status-unknown-wash)',
        },
        evidence: {
          observed: 'var(--evidence-observed)',
          'observed-wash': 'var(--evidence-observed-wash)',
          strong: 'var(--evidence-strong)',
          'strong-wash': 'var(--evidence-strong-wash)',
          inferred: 'var(--evidence-inferred)',
          'inferred-wash': 'var(--evidence-inferred-wash)',
          unknown: 'var(--evidence-unknown)',
          'unknown-wash': 'var(--evidence-unknown-wash)',
        },
        kind: {
          workflow: 'var(--kind-workflow)',
          'workflow-wash': 'var(--kind-workflow-wash)',
          'compiled-workflow': 'var(--kind-compiled-workflow)',
          'compiled-workflow-wash': 'var(--kind-compiled-workflow-wash)',
          agent: 'var(--kind-agent)',
          'agent-wash': 'var(--kind-agent-wash)',
          skill: 'var(--kind-skill)',
          'skill-wash': 'var(--kind-skill-wash)',
          instruction: 'var(--kind-instruction)',
          'instruction-wash': 'var(--kind-instruction-wash)',
          prompt: 'var(--kind-prompt)',
          'prompt-wash': 'var(--kind-prompt-wash)',
          hook: 'var(--kind-hook)',
          'hook-wash': 'var(--kind-hook-wash)',
          'mcp-server': 'var(--kind-mcp-server)',
          'mcp-server-wash': 'var(--kind-mcp-server-wash)',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        mono: ['"SFMono-Regular"', 'Consolas', '"Liberation Mono"', 'Menlo', 'monospace'],
      },
      boxShadow: {
        raised: 'var(--shadow-raised)',
        overlay: 'var(--shadow-overlay)',
      },
      borderRadius: {
        xl: '10px',
      },
    },
  },
  plugins: [],
};
